---
- name: Ensure that the destination directory exists
  file:
    path: '{{ solr_cloud_backup.dest.path }}/{{ solr_cloud_backup.collection.name }}'
    owner: '{{ solr_cloud_backup_owner }}'
    group: '{{ solr_cloud_backup_group }}'
    state: directory
  when: solr_cloud_backup.dest.path is defined

- name: Copy temp directory to file destination
  synchronize:
    src: '{{ temp_dir }}'
    dest: '{{ solr_cloud_backup.dest.path }}/{{ solr_cloud_backup.collection.name }}'
    mode: pull
  when: solr_cloud_backup.dest.path is defined