---
- name: Backup Solr Cloud collection
  uri:
    url: '{{ sc_base_url }}/replication?'
    body: '{{ sc_backup_params | join("&") }}'
    method: POST
    creates: '{{ item.location | d (sc_backup_location) }}/snapshot.{{ item.name }}-{{ ansible_date_time.epoch }}'
  run_once: yes
  loop: '{{ sc_backup_list }}'
  register: sc_backup_collection

- name: SC BACKUP COLLECTION
  debug:
    var: sc_backup_collection

- name: Create list of snapshot paths
  set_fact:
    snapshot_paths: '{{ sc_backup_collection.results | map(attribute="invocation") | sum(start=[]) | map(attribute="module_args") | map(attribute="creates") | reject("undefined") | list }}'

- name: Display snapshot paths
  debug:
    var: snapshot_paths
    