---
- name: Get list of snapshot dir folders
  set_fact:
    snapshot_dir_list: '{{ snapshot_dir_list | d ([]) + [item | dirname] }}'
  loop: '{{ snapshot_paths }}'

- name: Find snapshot folders
  find:
    paths: '{{ snapshot_dir_list }}'
    patterns: 'snapshot*'
    use_regex: yes
    file_type: directory
  register: find_snapshot_folders

- debug:
    var: find_snapshot_folders

- pause:

- name: Cleanup snapshot directories on shared drive space
  file: 
    path: '{{ item.location | d (sc_backup_location) }}/snapshot*'
    state: absent
  when: sc_backup_location_cleanup