---
# tasks file for emorylib_solr_cloud_backup_to_s3

- name: Include tasks for backup solr cloud
  include_tasks:
    file: backup-solr-cloud.yml

- name: Include task for moving backup to final destination
  include_tasks:
    file: backup-destination.yml
